services:

  sender:

    build: ./server/sender

    container_name: oil-sender

    restart: unless-stopped

    environment:
      TZ: "Europe/Moscow"

    ports:
      - 5000:5000

    command: gunicorn main:app -w 2 -b 0.0.0.0:5000 --reload

    networks:
      - back_net

    volumes:
      - ./server/sender:/service
      - ./media:/media
      - ./server/raw_data:/raw_data

    depends_on:
      - rabbitmq


  worker:

    build: ./server/recipient

    container_name: oil-worker

    restart: unless-stopped

    environment:
      TZ: "Europe/Moscow"

    command: python3 ./main.py

    networks:
      - back_net

    volumes:
      - ./server/recipient:/service
      - ./media:/media
      - ./server/raw_data:/raw_data

    depends_on:
      - rabbitmq
      - sender


  rabbitmq:

    image: rabbitmq:management-alpine

    container_name: oil-rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: always

    networks:
      - back_net

  # nginx:

  #   build: ./dist

  #   container_name: oil-static
    
  #   ports:
  #     - "80:80"
    
  #   volumes:
  #     - ./dist/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./media:/media

  #   networks:
  #     - back_net

networks:
  back_net:
    name: back_net
    external: true
