services:

  server:

    build: ./server

    container_name: oil-worker

    restart: unless-stopped

    environment:
      TZ: "Europe/Moscow"

    ports:
      - 5000:5000

    command: gunicorn main:app -w 2 -b 0.0.0.0:5000 --reload

    networks:
      - back_net

    volumes:
      - ./server:/service
      - ./media:/media

  nginx:

    build: ./dist

    container_name: oil-static
    
    ports:
      - "80:80"
    
    volumes:
      - ./dist/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/media

    networks:
      - back_net


networks:
  back_net:
    name: back_net
    external: true
