services:

  sender:

    build: ./server/sender

    container_name: oil-sender

    restart: unless-stopped

    environment:
      TZ: "Europe/Moscow"

    env_file:
      - ./.env

    ports:
      - 5000:5000

    command: gunicorn main:app -w ${SENDERS_QUANTITY} -b 0.0.0.0:5000 --reload

    networks:
      - back_net

    volumes:
      - ./server/sender:/service
      - ${PATH_TO_SAVE}:/media

    depends_on:
      - rabbitmq


  worker:

    build: ./server/recipient

    container_name: oil-worker

    restart: unless-stopped

    environment:
      TZ: "Europe/Moscow"

    env_file:
      - ./.env

    command: python3 ./main.py

    networks:
      - back_net

    volumes:
      - ./server/recipient:/service
      - ${PATH_TO_SAVE}:/media

    depends_on:
      - rabbitmq
      - sender


  rabbitmq:

    image: rabbitmq:alpine

    container_name: oil-rabbitmq

    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}

    ports:
      - 5672:5672

    restart: always

    networks:
      - back_net

  # nginx:

  #   build: ./dist

  #   container_name: oil-static
    
  #   ports:
  #     - "80:80"
    
  #   volumes:
  #     - ./dist/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./media:/media

  #   networks:
  #     - back_net

networks:
  back_net:
    name: back_net
    external: true
