name: mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  context_storage: ^1.0.0+1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  file_picker: ^8.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  http: ^1.2.1
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
